<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use \dmstr\bootstrap\Tabs;
use yii\helpers\StringHelper;
use kartik\date\DatePicker;

/**
* @var yii\web\View $this
* @var app\models\Launch $model
* @var yii\widgets\ActiveForm $form
*/

?>

<div class="launch-form">

	<?php $form = ActiveForm::begin(
		[
			'id' => 'Launch',
			'layout' => 'horizontal',
			'enableClientValidation' => true,
			'errorSummaryCssClass' => 'error-summary alert alert-danger',
			'fieldConfig' => [
				'template' => "{label}\n{beginWrapper}\n{input}\n{hint}\n{error}\n{endWrapper}",
				'horizontalCssClasses' => [
					'label' => 'col-sm-2',
					#'offset' => 'col-sm-offset-4',
					'wrapper' => 'col-sm-8',
					'error' => '',
					'hint' => '',
				],
			],
		]
	);
	?>

	<div class="">
		<?php $this->beginBlock('main'); ?>

		<p>


			<!-- attribute towplane_id -->
			<?= // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::activeField
			$form->field($model, 'towplane_id')->dropDownList(
				\yii\helpers\ArrayHelper::map(app\models\Towplane::find()->all(), 'id', 'rego'),
				[
					'prompt' => 'Select',
					'disabled' => (isset($relAttributes) && isset($relAttributes['towplane_id']))||!$model->isNewRecord,
				]
			); ?>

			<!-- attribute pilot_id -->
			<?= // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::activeField
			$form->field($model, 'pilot_id')->dropDownList(
				\yii\helpers\ArrayHelper::map(app\models\Pilot::find()->all(), 'id', 'rego_short'),
				[
					'prompt' => 'Select',
					'disabled' => (isset($relAttributes) && isset($relAttributes['pilot_id']))||!$model->isNewRecord,
				]
			); ?>

			<!-- attribute date -->
			<?php $model->date = $model->date ?? date('Y-m-d') ?>
			<?= '' //$form->field($model, 'date')->textInput() ?>
			<?php
			echo $form->field($model, 'date')->widget(DatePicker::classname(), [
				'type' => DatePicker::TYPE_COMPONENT_PREPEND,
				'pluginOptions' => [
					'autoclose' => true,
					'todayHighlight' => true,
					'todayBtn' => true,
					'format' => 'yyyy-mm-dd'
				]
			]);
			?>

			<!-- attribute transaction_id -->
			<?= ''
			// generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::activeField
			//$form->field($model, 'transaction_id')->dropDownList(
			//	\yii\helpers\ArrayHelper::map(app\models\Transaction::find()->all(), 'id', 'id'),
			//	[
			//		'prompt' => 'Select',
			//		'disabled' => (isset($relAttributes) && isset($relAttributes['transaction_id'])),
			//	]
			//); 
			?>
		</p>
		<?php $this->endBlock(); ?>

		<?=
		Tabs::widget(
			[
				'encodeLabels' => false,
				'items' => [
					[
						'label'   => Yii::t('models', 'Launch'),
						'content' => $this->blocks['main'],
						'active'  => true,
					],
				]
			]
		);
		?>
		<hr/>

		<?php echo $form->errorSummary($model); ?>

		<?= Html::submitButton(
			'<span class="glyphicon glyphicon-check"></span> ' .
			($model->isNewRecord ? 'Confirm Launch' : 'Update Launch'),
			[
				'id' => 'save-' . $model->formName(),
				'class' => 'btn btn-success'
			]
		);
		?>

		<?php ActiveForm::end(); ?>

	</div>

</div>

