<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\grid\GridView;
use kartik\date\DatePicker;

/**
* @var yii\web\View $this
* @var yii\data\ActiveDataProvider $dataProvider
* @var app\models\search\Launch $searchModel
*/

$this->title = Yii::t('models', 'Launches');
$this->params['breadcrumbs'][] = $this->title;


/**
* create action column template depending acces rights
*/
$actionColumnTemplates = [];

if (\Yii::$app->user->can('app_launch_view', ['route' => true])) {
	$actionColumnTemplates[] = '{view}';
}

if (\Yii::$app->user->can('app_launch_update', ['route' => true])) {
	$actionColumnTemplates[] = '{update}';
}

if (\Yii::$app->user->can('app_launch_delete', ['route' => true])) {
	$actionColumnTemplates[] = '{delete}';
}
if (isset($actionColumnTemplates)) {
	$actionColumnTemplate = implode(' ', $actionColumnTemplates);
	$actionColumnTemplateString = $actionColumnTemplate;
} else {
	Yii::$app->view->params['pageButtons'] = Html::a('<span class="glyphicon glyphicon-plus"></span> ' . 'New', ['create'], ['class' => 'btn btn-success']);
	$actionColumnTemplateString = "{view} {update} {delete}";
}
$actionColumnTemplateString = '<div class="action-buttons">'.$actionColumnTemplateString.'</div>';
?>
<div class="giiant-crud launch-index">

	<?php
	//             echo $this->render('_search', ['model' =>$searchModel]);
	?>


	<?php \yii\widgets\Pjax::begin(['id'=>'pjax-main', 'enableReplaceState'=> false, 'linkSelector'=>'#pjax-main ul.pagination a, th a', 'clientOptions' => ['pjax:success'=>'function(){alert("yo")}']]) ?>

	<h1>
		<?= Yii::t('models', 'Launches') ?>
		<small>
			List
		</small>
	</h1>
	<div class="clearfix crud-navigation">
		<?php
		if (\Yii::$app->user->can('app_launch_create', ['route' => true])) {
		?>
			<div class="pull-left">
				<?= Html::a('<span class="glyphicon glyphicon-plus"></span> ' . 'Update Launch List', ['manage'], ['class' => 'btn btn-success']) ?>
			</div>
		<?php
		}
		?>
		<div class="pull-right">

			<?php if (\Yii::$app->user->can('app_launch_create', ['route' => true])) { ?>
				<?=
				\yii\bootstrap\ButtonDropdown::widget(
					[
						'id' => 'giiant-relations',
						'encodeLabel' => false,
						'label' => '<span class="glyphicon glyphicon-paperclip"></span> ' . 'Relations',
						'dropdown' => [
							'options' => [
								'class' => 'dropdown-menu-right'
							],
							'encodeLabels' => false,
							'items' => [
								[
									'url' => ['pilot/index'],
									'label' => '<i class="glyphicon glyphicon-arrow-left"></i> ' . Yii::t('models', 'Pilot'),
								],
								[
									'url' => ['towplane/index'],
									'label' => '<i class="glyphicon glyphicon-arrow-left"></i> ' . Yii::t('models', 'Towplane'),
								],
								[
									'url' => ['transaction/index'],
									'label' => '<i class="glyphicon glyphicon-arrow-left"></i> ' . Yii::t('models', 'Transaction'),
								],

							]
						],
						'options' => [
							'class' => 'btn-default'
						]
					]
				);
				?>
			</div>
		<?php } ?>
	</div>

	<hr />

	<div class="table-responsive">
		<?= GridView::widget([
			'dataProvider' => $dataProvider,
			'pager' => [
				'class' => yii\widgets\LinkPager::class,
				'firstPageLabel' => 'First',
				'lastPageLabel' => 'Last',
			],
			'filterModel' => $searchModel,
			'tableOptions' => ['class' => 'table table-striped table-bordered table-hover'],
			'headerRowOptions' => ['class'=>'x'],
			'columns' => [
				[
					'attribute'=>'date',
					'value' =>'date',
					'filter'=>DatePicker::widget([
						'model' => $searchModel,
						'attribute'=>'date',
						'pluginOptions' => [
							'autoclose' => true,
							'todayHighlight' => true,
							'todayBtn' => true,
							'format' => 'yyyy-mm-dd'
						]
					])       
				],
				// generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::columnFormat
				[
					'class' => yii\grid\DataColumn::class,
					'attribute' => 'pilot_id',
					'value' => function ($model) {
						if ($rel = $model->pilot) {
							return Html::a($rel->rego_short, ['pilot/view', 'id' => $rel->id,], ['data-pjax' => 0]);
						} else {
							return '';
						}
					},
					'format' => 'raw',
				],
				[
					'class' => yii\grid\DataColumn::class,
					'attribute' => 'pilot_id',
					'value' => function ($model) {
						if ($rel = $model->pilot) {
							return Html::a($rel->person->name, ['pilot/view', 'id' => $rel->id,], ['data-pjax' => 0]);
						} else {
							return '';
						}
					},
					'label' => 'Pilot',
					'format' => 'raw',
				],
				// generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::columnFormat
				[
					'class' => yii\grid\DataColumn::class,
					'attribute' => 'towplane_id',
					'value' => function ($model) {
						if ($rel = $model->towplane) {
							return Html::a($rel->name, ['towplane/view', 'id' => $rel->id,], ['data-pjax' => 0]);
						} else {
							return '';
						}
					},
					'format' => 'raw',
				],
				// generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::columnFormat
				//[
				//	'class' => yii\grid\DataColumn::class,
				//	'attribute' => 'transaction_id',
				//	'value' => function ($model) {
				//		if ($rel = $model->transaction) {
				//			return Html::a($rel->id, ['transaction/view', 'id' => $rel->id,], ['data-pjax' => 0]);
				//		} else {
				//			return '';
				//		}
				//	},
				//	'format' => 'raw',
				//],
				[
					'class' => 'yii\grid\ActionColumn',
					'template' => $actionColumnTemplateString,
					'buttons' => [
						'view' => function ($url, $model, $key) {
							$options = [
								'title' => Yii::t('cruds', 'View'),
								'aria-label' => Yii::t('cruds', 'View'),
								'data-pjax' => '0',
							];
							return Html::a('<span class="glyphicon glyphicon-eye-open"></span>', $url, $options);
						}
					],
					'urlCreator' => function ($action, $model, $key, $index) {
						// using the column name as key, not mapping to 'id' like the standard generator
						$params = is_array($key) ? $key : [$model->primaryKey()[0] => (string) $key];
						$params[0] = \Yii::$app->controller->id ? \Yii::$app->controller->id . '/' . $action : $action;
						return Url::toRoute($params);
					},
					'contentOptions' => ['nowrap'=>'nowrap']
				],
			]
		]); ?>
	</div>

</div>


<?php \yii\widgets\Pjax::end() ?>


