<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use \dmstr\bootstrap\Tabs;
use yii\helpers\StringHelper;
use richardfan\widget\JSRegister;

/**
 * @var yii\web\View $this
 * @var app\models\Towplane $model
 * @var yii\widgets\ActiveForm $form
 */

?>

<div class="towplane-form">

    <?php $form = ActiveForm::begin(
        [
            'id' => 'Towplane',
            'layout' => 'horizontal',
            'enableClientValidation' => true,
            'errorSummaryCssClass' => 'error-summary alert alert-danger',
            'fieldConfig' => [
                'template' => "{label}\n{beginWrapper}\n{input}\n{hint}\n{error}\n{endWrapper}",
                'horizontalCssClasses' => [
                    'label' => 'col-sm-2',
                    #'offset' => 'col-sm-offset-4',
                    'wrapper' => 'col-sm-8',
                    'error' => '',
                    'hint' => '',
                ],
            ],
        ]
    );
    ?>

    <div class="">
        <?php $this->beginBlock('main'); ?>

        <p>


            <!-- attribute contest_id -->
            <?= // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::activeField
            $form->field($model, 'contest_id')->dropDownList(
                \yii\helpers\ArrayHelper::map(app\models\Contest::find()->all(), 'id', 'name'),
                [
                    'prompt' => 'Select',
                    'disabled' => (isset($relAttributes) && isset($relAttributes['contest_id'])) || !$model->isNewRecord,
                ]
            ); ?>

            <!-- attribute rego -->
            <?= $form->field($model, 'rego')->dropDownList(
                \yii\helpers\ArrayHelper::map(app\models\MasterTowplane::find()->all(), 'rego', 'rego'),
                [
                    'prompt' => 'Select',
                    'disabled' => (isset($relAttributes) && isset($relAttributes['rego'])) || !$model->isNewRecord,
                ]
            ); ?>
            <!-- attribute description -->
            <?= $form->field($model, 'description')->textInput(['maxlength' => true]) ?>

            <!-- attribute name -->
            <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>

            <!-- attribute address1 -->
            <?= $form->field($model, 'address1')->textInput(['maxlength' => true]) ?>

            <!-- attribute address2 -->
            <?= $form->field($model, 'address2')->textInput(['maxlength' => true]) ?>

            <!-- attribute address3 -->
            <?= $form->field($model, 'address3')->textInput(['maxlength' => true]) ?>

            <!-- attribute postcode -->
            <?= $form->field($model, 'postcode')->textInput(['maxlength' => true]) ?>

            <!-- attribute telephone -->
            <?= $form->field($model, 'telephone')->textInput(['maxlength' => true]) ?>
        </p>
        <?php $this->endBlock(); ?>

        <?=
        Tabs::widget(
            [
                'encodeLabels' => false,
                'items' => [
                    [
                        'label'   => Yii::t('models', 'Towplane'),
                        'content' => $this->blocks['main'],
                        'active'  => true,
                    ],
                ]
            ]
        );
        ?>
        <hr />

        <?php echo $form->errorSummary($model); ?>

        <?= Html::submitButton(
            '<span class="glyphicon glyphicon-check"></span> ' .
                ($model->isNewRecord ? 'Create' : 'Save'),
            [
                'id' => 'save-' . $model->formName(),
                'class' => 'btn btn-success'
            ]
        );
        ?>

        <?php ActiveForm::end(); ?>

    </div>

</div>

<?php JSRegister::begin(); ?>

<script>
    $('#towplane-rego').change(function(e) {
        $.ajax({
            url: 'master',
            data: {
                rego: $('#towplane-rego').val()
            },
            success: function(data) {
                $('#towplane-description').val(data['description']);
                $('#towplane-name').val(data['name']);
                $('#towplane-address1').val(data['address1']);
                $('#towplane-address2').val(data['address2']);
                $('#towplane-address3').val(data['address3']);
                $('#towplane-postcode').val(data['postcode']);
                $('#towplane-telephone').val(data['telephone']);
            }
        });
    });
</script>

<?php JSRegister::end(); ?>