<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "clubs".
 *
 * @property integer $id
 * @property string $name
 * @property string $address1
 * @property string $address2
 * @property string $address3
 * @property string $postcode
 * @property string $telephone
 * @property string $email
 * @property string $bankname
 * @property string $bankno
 * @property string $gstno
 *
 * @property \app\models\Contest[] $contests
 * @property string $aliasModel
 */
abstract class Club extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'clubs';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name', 'address1'], 'required'],
            [['name', 'address1', 'address2', 'address3'], 'string', 'max' => 80],
            [['postcode'], 'string', 'max' => 8],
            [['telephone', 'bankno', 'gstno'], 'string', 'max' => 16],
            [['email'], 'string', 'max' => 100],
            [['bankname'], 'string', 'max' => 40]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Club Name',
            'address1' => 'Address Line 1',
            'address2' => 'Address Line 2',
            'address3' => 'Address Line 3',
            'postcode' => 'Post Code',
            'telephone' => 'Telephone',
            'email' => 'E Mail',
            'bankname' => 'Bank Name',
            'bankno' => 'Account Number',
            'gstno' => 'GST Number',
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return array_merge(parent::attributeHints(), [
            'name' => 'Club Name',
            'address1' => 'Address Line 1',
            'address2' => 'Address Line 2',
            'address3' => 'Address Line 3',
            'postcode' => 'Post Code',
            'telephone' => 'Telephone',
            'email' => 'E Mail',
            'bankname' => 'Bank Name',
            'bankno' => 'Account Number',
            'gstno' => 'GST Number',
        ]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getContests()
    {
        return $this->hasMany(\app\models\Contest::className(), ['club_id' => 'id']);
    }


    
    /**
     * @inheritdoc
     * @return \app\models\query\ClubQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \app\models\query\ClubQuery(get_called_class());
    }


}
