<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "contests".
 *
 * @property integer $id
 * @property integer $club_id
 * @property integer $gnz_id
 * @property string $name
 * @property string $start
 * @property string $end
 * @property string $igcfiles
 *
 * @property \app\models\Club $club
 * @property \app\models\Person[] $people
 * @property \app\models\Pilot[] $pilots
 * @property \app\models\Towplane[] $towplanes
 * @property \app\models\TransactionType[] $transactionTypes
 * @property string $aliasModel
 */
abstract class Contest extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'contests';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['club_id', 'name', 'start', 'end', 'igcfiles'], 'required'],
            [['club_id', 'gnz_id'], 'integer'],
            [['start', 'end'], 'safe'],
            [['name'], 'string', 'max' => 80],
            [['igcfiles'], 'string', 'max' => 12],
            [['name'], 'unique'],
            [['club_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Club::className(), 'targetAttribute' => ['club_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'club_id' => 'Club ID',
            'gnz_id' => 'GNZ Contest ID',
            'name' => 'Contest Name',
            'start' => 'Start Date',
            'end' => 'End Date',
            'igcfiles' => 'IGC Uploads Directory',
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return array_merge(parent::attributeHints(), [
            'gnz_id' => 'GNZ Contest ID',
            'name' => 'Contest Name',
            'start' => 'Start Date',
            'end' => 'End Date',
            'igcfiles' => 'IGC Uploads Directory',
        ]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getClub()
    {
        return $this->hasOne(\app\models\Club::className(), ['id' => 'club_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPeople()
    {
        return $this->hasMany(\app\models\Person::className(), ['contest_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPilots()
    {
        return $this->hasMany(\app\models\Pilot::className(), ['contest_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTowplanes()
    {
        return $this->hasMany(\app\models\Towplane::className(), ['contest_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTransactionTypes()
    {
        return $this->hasMany(\app\models\TransactionType::className(), ['contest_id' => 'id']);
    }


    
    /**
     * @inheritdoc
     * @return \app\models\query\ContestQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \app\models\query\ContestQuery(get_called_class());
    }


}
