<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "defaultTypes".
 *
 * @property integer $id
 * @property string $name
 * @property string $description
 * @property string $price
 * @property string $credit
 * @property string $aliasModel
 */
abstract class DefaultType extends \yii\db\ActiveRecord
{



    /**
    * ENUM field values
    */
    const CREDIT_DEBIT = 'Debit';
    const CREDIT_CREDIT = 'Credit';
    var $enum_labels = false;
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'defaultTypes';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name', 'description', 'credit'], 'required'],
            [['price'], 'number'],
            [['credit'], 'string'],
            [['name'], 'string', 'max' => 12],
            [['description'], 'string', 'max' => 80],
            ['credit', 'in', 'range' => [
                    self::CREDIT_DEBIT,
                    self::CREDIT_CREDIT,
                ]
            ]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Short Name',
            'description' => 'Item Description',
            'price' => 'Usual Price',
            'credit' => 'Debit or Credit Item',
        ];
    }


    
    /**
     * @inheritdoc
     * @return \app\models\query\DefaultTypeQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \app\models\query\DefaultTypeQuery(get_called_class());
    }


    /**
     * get column credit enum value label
     * @param string $value
     * @return string
     */
    public static function getCreditValueLabel($value){
        $labels = self::optsCredit();
        if(isset($labels[$value])){
            return $labels[$value];
        }
        return $value;
    }

    /**
     * column credit ENUM value labels
     * @return array
     */
    public static function optsCredit()
    {
        return [
            self::CREDIT_DEBIT => 'Debit',
            self::CREDIT_CREDIT => 'Credit',
        ];
    }

}
