<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "landouts".
 *
 * @property integer $id
 * @property integer $pilot_id
 * @property string $date
 * @property string $landed_at
 * @property string $departed_at
 * @property string $returned_at
 * @property string $lat
 * @property string $lng
 * @property string $address
 * @property string $trailer
 * @property string $plate
 * @property string $crew
 * @property string $crew_phone
 * @property string $notes
 * @property string $status
 *
 * @property \app\models\Pilot $pilot
 * @property string $aliasModel
 */
abstract class Landout extends \yii\db\ActiveRecord
{



    /**
    * ENUM field values
    */
    const STATUS_AWAITING_CREW = 'Awaiting Crew';
    const STATUS_CREW_DEPARTED = 'Crew Departed';
    const STATUS_RETURNED = 'Returned';
    var $enum_labels = false;
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'landouts';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['pilot_id', 'date', 'landed_at'], 'required'],
            [['pilot_id'], 'integer'],
            [['date', 'landed_at', 'departed_at', 'returned_at'], 'safe'],
            [['lat', 'lng'], 'number'],
            [['address', 'notes', 'status'], 'string'],
            [['trailer', 'crew'], 'string', 'max' => 80],
            [['plate'], 'string', 'max' => 10],
            [['crew_phone'], 'string', 'max' => 16],
            [['pilot_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Pilot::className(), 'targetAttribute' => ['pilot_id' => 'id']],
            ['status', 'in', 'range' => [
                    self::STATUS_AWAITING_CREW,
                    self::STATUS_CREW_DEPARTED,
                    self::STATUS_RETURNED,
                ]
            ]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'Land Out',
            'pilot_id' => 'Pilot',
            'date' => 'Landout Date',
            'landed_at' => 'Landout Time',
            'departed_at' => 'Crew Departed At',
            'returned_at' => 'Pilot Returned At',
            'lat' => 'Latitude',
            'lng' => 'Longitude',
            'address' => 'Address',
            'trailer' => 'Trailer Details',
            'plate' => 'Car Plate',
            'crew' => 'Crew Name',
            'crew_phone' => 'Crew Phone',
            'notes' => 'Notes',
            'status' => 'Status',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPilot()
    {
        return $this->hasOne(\app\models\Pilot::className(), ['id' => 'pilot_id']);
    }


    
    /**
     * @inheritdoc
     * @return \app\models\query\LandoutQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \app\models\query\LandoutQuery(get_called_class());
    }


    /**
     * get column status enum value label
     * @param string $value
     * @return string
     */
    public static function getStatusValueLabel($value){
        $labels = self::optsStatus();
        if(isset($labels[$value])){
            return $labels[$value];
        }
        return $value;
    }

    /**
     * column status ENUM value labels
     * @return array
     */
    public static function optsStatus()
    {
        return [
            self::STATUS_AWAITING_CREW => 'Awaiting Crew',
            self::STATUS_CREW_DEPARTED => 'Crew Departed',
            self::STATUS_RETURNED => 'Returned',
        ];
    }

}
