<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "launches".
 *
 * @property integer $id
 * @property integer $towplane_id
 * @property integer $pilot_id
 * @property string $date
 * @property integer $transaction_id
 *
 * @property \app\models\Pilot $pilot
 * @property \app\models\Towplane $towplane
 * @property \app\models\Transaction $transaction
 * @property string $aliasModel
 */
abstract class Launch extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'launches';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['towplane_id', 'pilot_id', 'date'], 'required'],
            [['towplane_id', 'pilot_id', 'transaction_id'], 'integer'],
            [['date'], 'safe'],
            [['pilot_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Pilot::class, 'targetAttribute' => ['pilot_id' => 'id']],
            [['towplane_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Towplane::class, 'targetAttribute' => ['towplane_id' => 'id']],
            [['transaction_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Transaction::class, 'targetAttribute' => ['transaction_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'towplane_id' => 'Towplane',
            'pilot_id' => 'Glider',
            'date' => 'Launch Date',
            'transaction_id' => 'Account Transaction ID',
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return array_merge(parent::attributeHints(), [
            'towplane_id' => 'Towplane',
            'pilot_id' => 'Glider',
            'date' => 'Launch Date',
            'transaction_id' => 'Account Transaction ID',
        ]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPilot()
    {
        return $this->hasOne(\app\models\Pilot::class, ['id' => 'pilot_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTowplane()
    {
        return $this->hasOne(\app\models\Towplane::class, ['id' => 'towplane_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTransaction()
    {
        return $this->hasOne(\app\models\Transaction::class, ['id' => 'transaction_id']);
    }


    
    /**
     * @inheritdoc
     * @return \app\models\query\LaunchQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \app\models\query\LaunchQuery(get_called_class());
    }


}
