<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "masterTowplanes".
 *
 * @property integer $id
 * @property string $rego
 * @property string $description
 * @property string $name
 * @property string $address1
 * @property string $address2
 * @property string $address3
 * @property string $postcode
 * @property string $telephone
 * @property string $aliasModel
 */
abstract class MasterTowplane extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'masterTowplanes';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['rego', 'description', 'name', 'address1'], 'required'],
            [['rego'], 'string', 'max' => 4],
            [['description', 'name', 'address1', 'address2', 'address3'], 'string', 'max' => 80],
            [['postcode'], 'string', 'max' => 8],
            [['telephone'], 'string', 'max' => 12]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'rego' => 'Towplane Registration',
            'description' => 'Description',
            'name' => 'Name',
            'address1' => 'Address Line 1',
            'address2' => 'Address Line 2',
            'address3' => 'Address Line 3',
            'postcode' => 'Post Code',
            'telephone' => 'Phone',
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return array_merge(parent::attributeHints(), [
            'rego' => 'Towplane Registration',
            'description' => 'Description',
            'name' => 'Name',
            'address1' => 'Address Line 1',
            'address2' => 'Address Line 2',
            'address3' => 'Address Line 3',
            'postcode' => 'Post Code',
            'telephone' => 'Phone',
        ]);
    }


    
    /**
     * @inheritdoc
     * @return \app\models\query\MasterTowplaneQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \app\models\query\MasterTowplaneQuery(get_called_class());
    }


}
