<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "persons".
 *
 * @property integer $id
 * @property integer $contest_id
 * @property string $name
 * @property string $role
 * @property string $telephone
 *
 * @property \app\models\Contest $contest
 * @property string $aliasModel
 */
abstract class Person extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'persons';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['contest_id', 'name', 'telephone'], 'required'],
            [['contest_id'], 'integer'],
            [['telephone'], 'string'],
            [['name'], 'string', 'max' => 80],
            [['role'], 'string', 'max' => 40],
            [['contest_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Contest::className(), 'targetAttribute' => ['contest_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'contest_id' => 'Contest Name',
            'name' => 'Persons Name',
            'role' => 'Contest Role',
            'telephone' => 'Mobile Contact Number for SMS',
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return array_merge(parent::attributeHints(), [
            'id' => 'ID',
            'contest_id' => 'Contest Name',
            'name' => 'Persons Name',
            'role' => 'Contest Role',
            'telephone' => 'Mobile Contact Number for SMS',
        ]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getContest()
    {
        return $this->hasOne(\app\models\Contest::className(), ['id' => 'contest_id']);
    }


    
    /**
     * @inheritdoc
     * @return \app\models\query\PersonQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \app\models\query\PersonQuery(get_called_class());
    }


}
