<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "pilots".
 *
 * @property integer $id
 * @property integer $contest_id
 * @property integer $gnz_id
 * @property string $name
 * @property string $address1
 * @property string $address2
 * @property string $address3
 * @property string $postcode
 * @property string $telephone
 * @property string $rego
 * @property string $rego_short
 * @property string $entry_date
 * @property string $trailer
 * @property string $plate
 * @property string $crew
 * @property string $crew_phone
 *
 * @property \app\models\Landout[] $landouts
 * @property \app\models\Launch[] $launches
 * @property \app\models\Contest $contest
 * @property \app\models\Retrieve[] $retrieves
 * @property \app\models\Transaction[] $transactions
 * @property string $aliasModel
 */
abstract class Pilot extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'pilots';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['contest_id', 'name', 'address1', 'rego', 'rego_short', 'entry_date'], 'required'],
            [['contest_id', 'gnz_id'], 'integer'],
            [['entry_date'], 'safe'],
            [['name', 'address1', 'address2', 'address3', 'trailer', 'crew'], 'string', 'max' => 80],
            [['postcode'], 'string', 'max' => 12],
            [['telephone', 'crew_phone'], 'string', 'max' => 16],
            [['rego'], 'string', 'max' => 6],
            [['rego_short'], 'string', 'max' => 2],
            [['plate'], 'string', 'max' => 10],
            [['contest_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Contest::className(), 'targetAttribute' => ['contest_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'contest_id' => 'Contest ID',
            'gnz_id' => 'GNZ Pilot ID',
            'name' => 'Name',
            'address1' => 'Address Line 1',
            'address2' => 'Address Line 2',
            'address3' => 'Address Line 3',
            'postcode' => 'Post Code',
            'telephone' => 'Telephone',
            'rego' => 'Glider Registration',
            'rego_short' => 'Glider Contest ID',
            'entry_date' => 'Entry Date',
            'trailer' => 'Car & Trailer',
            'plate' => 'Car Plate',
            'crew' => 'Crew Name',
            'crew_phone' => 'Crew Phone',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getLandouts()
    {
        return $this->hasMany(\app\models\Landout::className(), ['pilot_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getLaunches()
    {
        return $this->hasMany(\app\models\Launch::className(), ['pilot_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getContest()
    {
        return $this->hasOne(\app\models\Contest::className(), ['id' => 'contest_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getRetrieves()
    {
        return $this->hasMany(\app\models\Retrieve::className(), ['pilot_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTransactions()
    {
        return $this->hasMany(\app\models\Transaction::className(), ['pilot_id' => 'id']);
    }


    
    /**
     * @inheritdoc
     * @return \app\models\query\PilotQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \app\models\query\PilotQuery(get_called_class());
    }


}
