<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "retrieves".
 *
 * @property integer $id
 * @property integer $towplane_id
 * @property integer $pilot_id
 * @property string $date
 * @property integer $duration
 * @property string $price
 * @property integer $transaction_id
 *
 * @property \app\models\Pilot $pilot
 * @property \app\models\Towplane $towplane
 * @property \app\models\Transaction $transaction
 * @property string $aliasModel
 */
abstract class Retrieve extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'retrieves';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['towplane_id', 'pilot_id', 'date', 'duration', 'price'], 'required'],
            [['towplane_id', 'pilot_id', 'duration', 'transaction_id'], 'integer'],
            [['date'], 'safe'],
            [['price'], 'number'],
            [['pilot_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Pilot::className(), 'targetAttribute' => ['pilot_id' => 'id']],
            [['towplane_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Towplane::className(), 'targetAttribute' => ['towplane_id' => 'id']],
            [['transaction_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Transaction::className(), 'targetAttribute' => ['transaction_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'towplane_id' => 'Towplane',
            'pilot_id' => 'Glider',
            'date' => 'Retrieve Date',
            'duration' => 'Retrive Duration',
            'price' => 'Retrieve Cost',
            'transaction_id' => 'Transaction',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPilot()
    {
        return $this->hasOne(\app\models\Pilot::className(), ['id' => 'pilot_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTowplane()
    {
        return $this->hasOne(\app\models\Towplane::className(), ['id' => 'towplane_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTransaction()
    {
        return $this->hasOne(\app\models\Transaction::className(), ['id' => 'transaction_id']);
    }


    
    /**
     * @inheritdoc
     * @return \app\models\query\RetrieveQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \app\models\query\RetrieveQuery(get_called_class());
    }


}
