<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "received_sms".
 *
 * @property integer $id
 * @property integer $from
 * @property string $sent
 * @property string $received
 * @property integer $sender_id
 * @property string $sender
 * @property string $message
 * @property string $aliasModel
 */
abstract class Sms extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'received_sms';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['from'], 'required'],
            [['from', 'sender_id'], 'integer'],
            [['sent', 'received'], 'safe'],
            [['message'], 'string'],
            [['sender'], 'string', 'max' => 80]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'from' => 'From',
            'sent' => 'Sent At',
            'received' => 'Received At',
            'sender_id' => 'Sender ID',
            'sender' => 'Sender Name',
            'message' => 'Message',
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return array_merge(parent::attributeHints(), [
            'from' => 'From',
            'sent' => 'Set At',
            'received' => 'Received At',
            'sender_id' => 'Sender ID',
            'sender' => 'Sender Name',
            'message' => 'Message',
        ]);
    }


    
    /**
     * @inheritdoc
     * @return \app\models\query\SmsQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \app\models\query\SmsQuery(get_called_class());
    }


}
