<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "towplanes".
 *
 * @property integer $id
 * @property integer $contest_id
 * @property string $rego
 * @property string $description
 * @property string $name
 * @property string $address1
 * @property string $address2
 * @property string $address3
 * @property string $postcode
 * @property string $telephone
 *
 * @property \app\models\Launch[] $launches
 * @property \app\models\Retrieve[] $retrieves
 * @property \app\models\Contest $contest
 * @property string $aliasModel
 */
abstract class Towplane extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'towplanes';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['contest_id', 'rego', 'description', 'name', 'address1'], 'required'],
            [['contest_id'], 'integer'],
            [['rego'], 'string', 'max' => 3],
            [['description', 'name', 'address1', 'address2', 'address3'], 'string', 'max' => 80],
            [['postcode'], 'string', 'max' => 8],
            [['telephone'], 'string', 'max' => 12],
            [['contest_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Contest::className(), 'targetAttribute' => ['contest_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'contest_id' => 'Contest',
            'rego' => 'Towplane Registration',
            'description' => 'Description',
            'name' => 'Name',
            'address1' => 'Address Line 1',
            'address2' => 'Address Line 2',
            'address3' => 'Address Line 3',
            'postcode' => 'Post Code',
            'telephone' => 'Phone',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getLaunches()
    {
        return $this->hasMany(\app\models\Launch::className(), ['towplane_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getRetrieves()
    {
        return $this->hasMany(\app\models\Retrieve::className(), ['towplane_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getContest()
    {
        return $this->hasOne(\app\models\Contest::className(), ['id' => 'contest_id']);
    }


    
    /**
     * @inheritdoc
     * @return \app\models\query\TowplaneQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \app\models\query\TowplaneQuery(get_called_class());
    }


}
