<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "transactions".
 *
 * @property integer $id
 * @property integer $person_id
 * @property integer $type_id
 * @property string $details
 * @property integer $quantity
 * @property string $item_price
 * @property string $amount
 * @property string $date
 *
 * @property \app\models\Launch[] $launches
 * @property \app\models\Retrieve[] $retrieves
 * @property \app\models\Person $person
 * @property \app\models\TransactionType $type
 * @property string $aliasModel
 */
abstract class Transaction extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'transactions';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['person_id', 'type_id', 'item_price', 'amount', 'date'], 'required'],
            [['person_id', 'type_id', 'quantity'], 'integer'],
            [['item_price', 'amount'], 'number'],
            [['date'], 'safe'],
            [['details'], 'string', 'max' => 80],
            [['person_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Person::class, 'targetAttribute' => ['person_id' => 'id']],
            [['type_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\TransactionType::class, 'targetAttribute' => ['type_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'person_id' => 'Person',
            'type_id' => 'Transaction Type',
            'details' => 'Details',
            'quantity' => 'Quantity',
            'item_price' => 'Item Price',
            'amount' => 'Total Price',
            'date' => 'Date',
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return array_merge(parent::attributeHints(), [
            'person_id' => 'Person',
            'type_id' => 'Transaction Type',
            'details' => 'Details',
            'quantity' => 'Quantity',
            'item_price' => 'Item Price',
            'amount' => 'Total Price',
            'date' => 'Date',
        ]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getLaunches()
    {
        return $this->hasMany(\app\models\Launch::class, ['transaction_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getRetrieves()
    {
        return $this->hasMany(\app\models\Retrieve::class, ['transaction_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPerson()
    {
        return $this->hasOne(\app\models\Person::class, ['id' => 'person_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getType()
    {
        return $this->hasOne(\app\models\TransactionType::class, ['id' => 'type_id']);
    }


    
    /**
     * @inheritdoc
     * @return \app\models\query\TransactionQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \app\models\query\TransactionQuery(get_called_class());
    }


}
