<?php

use yii\helpers\Html;
use yii\helpers\Url;
use kartik\grid\GridView;
use yii\widgets\DetailView;

?>

<?php


?>

<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
	<head>
		<meta charset="<?= Yii::$app->charset ?>">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<?php $this->registerCsrfMetaTags() ?>
		<title><?= Html::encode($this->title) ?></title>
		<?php $this->head() ?>
	</head>
	<body>
		<?php $this->beginBody() ?>
		<div class="container">
			<div class="body-content">

				<p></p>
				<p></p>

				<h1>
					<?= Yii::t('models', 'Landout Details : ') ?>
					<small>
						<?= Html::encode($model->pilot->rego) ?>
					</small>
				</h1>

				<div class="table-responsive">
					<?= DetailView::widget([
						'model' => $model,
						'attributes' => [
							// generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::attributeFormat
							'date',
							'pilot.rego',
							'pilot.person.name',
							'pilot.person.telephone',
							'trailer',
							'plate',
							//'landed_at',
							'lat',
							'lng',
							//'crew',
							//'crew_phone',
							'address:ntext',
							'notes:ntext',
						],
					]); ?>				
				</div>
			</div>
		</div>
	</body>
</html>
