<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\grid\GridView;
use yii\helpers\ArrayHelper;

/**
* @var yii\web\View $this
* @var yii\data\ActiveDataProvider $dataProvider
* @var app\models\search\Status $searchModel
*/

$this->title = Yii::t('models', 'Status');
$this->params['breadcrumbs'][] = $this->title;


/**
* create action column template depending acces rights
*/
$actionColumnTemplates = [];

if (\Yii::$app->user->can('app_status_view', ['route' => true])) {
	$actionColumnTemplates[] = '{view}';
}

if (\Yii::$app->user->can('app_status_update', ['route' => true])) {
	$actionColumnTemplates[] = '{update}';
}

if (\Yii::$app->user->can('app_status_delete', ['route' => true])) {
	$actionColumnTemplates[] = '{delete}';
}
if (isset($actionColumnTemplates)) {
	$actionColumnTemplate = implode(' ', $actionColumnTemplates);
	$actionColumnTemplateString = $actionColumnTemplate;
} else {
	Yii::$app->view->params['pageButtons'] = Html::a('<span class="glyphicon glyphicon-plus"></span> ' . 'New', ['create'], ['class' => 'btn btn-success']);
	$actionColumnTemplateString = "{view} {update} {delete}";
}
$actionColumnTemplateString = '<div class="action-buttons">'.$actionColumnTemplateString.'</div>';
?>
<div class="giiant-crud status-index">

	<?php
	//             echo $this->render('_search', ['model' =>$searchModel]);
	?>


	<?php \yii\widgets\Pjax::begin(['id'=>'pjax-main', 'enableReplaceState'=> false, 'linkSelector'=>'#pjax-main ul.pagination a, th a', 'clientOptions' => ['pjax:success'=>'function(){alert("yo")}']]) ?>

	<h1>
		<?= Yii::t('models', 'Status') ?>
		<small>
			Glider Status Updates
		</small>
	</h1>
	<div class="clearfix crud-navigation">
		<?php
		if(\Yii::$app->user->can('app_status_create', ['route' => true])){
		?>
			<div class="pull-left">
				<?= Html::a('<span class="glyphicon glyphicon-plus"></span> ' . 'Update Glider Status', ['manage'], ['class' => 'btn btn-success']) ?>
			</div>
		<?php
		}
		?>
		<div class="pull-right">


			<?= 
			\yii\bootstrap\ButtonDropdown::widget(
				[
					'id' => 'giiant-relations',
					'encodeLabel' => false,
					'label' => '<span class="glyphicon glyphicon-paperclip"></span> ' . 'Relations',
					'dropdown' => [
						'options' => [
							'class' => 'dropdown-menu-right'
						],
						'encodeLabels' => false,
						'items' => [
							[
								'url' => ['pilot/index'],
								'label' => '<i class="glyphicon glyphicon-arrow-left"></i> ' . Yii::t('models', 'Pilot'),
							],

						]
					],
					'options' => [
						'class' => 'btn-default'
					]
				]
			);
			?>
		</div>
	</div>

	<hr />

	<div class="table-responsive">
		<?= GridView::widget([
			'dataProvider' => $dataProvider,
			'pager' => [
				'class' => yii\widgets\LinkPager::class,
				'firstPageLabel' => 'First',
				'lastPageLabel' => 'Last',
			],
			'filterModel' => $searchModel,
			'tableOptions' => ['class' => 'table table-striped table-bordered table-hover'],
			'headerRowOptions' => ['class'=>'x'],
			'columns' => [
				/*
				[
				'class' => 'yii\grid\ActionColumn',
				'template' => $actionColumnTemplateString,
				'buttons' => [
				'view' => function ($url, $model, $key) {
				$options = [
				'title' => Yii::t('cruds', 'View'),
				'aria-label' => Yii::t('cruds', 'View'),
				'data-pjax' => '0',
				];
				return Html::a('<span class="glyphicon glyphicon-eye-open"></span>', $url, $options);
				}
				],
				'urlCreator' => function($action, $model, $key, $index) {
				// using the column name as key, not mapping to 'id' like the standard generator
				$params = is_array($key) ? $key : [$model->primaryKey()[0] => (string) $key];
				$params[0] = \Yii::$app->controller->id ? \Yii::$app->controller->id . '/' . $action : $action;
				return Url::toRoute($params);
				},
				'contentOptions' => ['nowrap'=>'nowrap']
				],
				*/
				[
					'attribute' => 'pilot_id',
					'value' => 'pilot.rego_short',
					'header' => 'Glider',
					'filter' => ArrayHelper::map(app\models\Pilot::find()->orderBy('rego_short ASC')->all(), 'id', 'rego_short'),
				],
				// generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::columnFormat
				[
					'class' => yii\grid\DataColumn::class,
					'attribute' => 'pilot_id',
					'value' => function ($model) {
						if ($rel = $model->pilot) {
							return Html::a($rel->person->name, ['pilot/view', 'id' => $rel->id,], ['data-pjax' => 0]);
						} else {
							return '';
						}
					},
					'format' => 'raw',
				],
				[
					'attribute'=>'status',
					'value' => function ($model) {
						return app\models\Status::getStatusValueLabel($model->status);
					}    
				],
				'date',
				'time',
			]
		]); ?>
	</div>

</div>


<?php \yii\widgets\Pjax::end() ?>


