<?php

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use \dmstr\bootstrap\Tabs;
use yii\helpers\StringHelper;

/**
* @var yii\web\View $this
* @var app\models\Contest $model
* @var yii\widgets\ActiveForm $form
*/

?>

<div class="contest-form">

	<?php $form = ActiveForm::begin(
		[
			'id' => 'Contest',
			'layout' => 'horizontal',
			'enableClientValidation' => true,
			'errorSummaryCssClass' => 'error-summary alert alert-danger',
			'fieldConfig' => [
				'template' => "{label}\n{beginWrapper}\n{input}\n{hint}\n{error}\n{endWrapper}",
				'horizontalCssClasses' => [
					'label' => 'col-sm-2',
					#'offset' => 'col-sm-offset-4',
					'wrapper' => 'col-sm-8',
					'error' => '',
					'hint' => '',
				],
			],
		]
	);
	?>

	<div class="">
		<?php $this->beginBlock('main'); ?>

		<p>


			<!-- attribute club_id -->
			<?= // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::activeField
			$form->field($model, 'club_id')->dropDownList(
				\yii\helpers\ArrayHelper::map(app\models\Club::find()->all(), 'id', 'name'),
				[
					'prompt' => 'Select',
					'disabled' => (isset($relAttributes) && isset($relAttributes['club_id'])),
				]
			); ?>
			<?=
			$form->field($model, 'gnz_id')->dropDownList(
				Yii::$app->gnz->getContestList(),
				[
					'prompt' => 'Select',
					'disabled' => (isset($relAttributes) && isset($relAttributes['gnz_id'])),
				]
			); ?>

			<!-- attribute igcfiles -->
			<?= $form->field($model, 'igcfiles')->textInput(['maxlength' => true]) ?>
		</p>
		<?php $this->endBlock(); ?>

		<?=
		Tabs::widget(
			[
				'encodeLabels' => false,
				'items' => [
					[
						'label'   => Yii::t('models', 'Contest'),
						'content' => $this->blocks['main'],
						'active'  => true,
					],
				]
			]
		);
		?>
		<hr/>

		<?php echo $form->errorSummary($model); ?>

		<?= Html::submitButton(
			'<span class="glyphicon glyphicon-check"></span> ' .
			($model->isNewRecord ? 'Create' : 'Save'),
			[
				'id' => 'save-' . $model->formName(),
				'class' => 'btn btn-success'
			]
		);
		?>

		<?php ActiveForm::end(); ?>

	</div>

</div>

