<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\grid\GridView;
use yii\widgets\DetailView;
use yii\widgets\Pjax;
use dmstr\bootstrap\Tabs;

/**
* @var yii\web\View $this
* @var app\models\Contest $model
*/
$copyParams = $model->attributes;

$this->title = Yii::t('models', 'Contest');
$this->params['breadcrumbs'][] = ['label' => Yii::t('models', 'Contests'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => (string)$model->name, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'View';
?>
<div class="giiant-crud contest-view">

	<!-- flash message -->
	<?php if (\Yii::$app->session->getFlash('deleteError') !== null) : ?>
		<span class="alert alert-info alert-dismissible" role="alert">
			<button type="button" class="close" data-dismiss="alert" aria-label="Close">
				<span aria-hidden="true">&times;</span></button>
			<?= \Yii::$app->session->getFlash('deleteError') ?>
		</span>
	<?php endif; ?>

	<h1>
		<?= Yii::t('models', 'Contest') ?>
		<small>
			<?= Html::encode($model->name) ?>
		</small>
	</h1>


	<div class="clearfix crud-navigation">

		<!-- menu buttons -->
		<div class='pull-left'>
			<?= Html::a(
				'<span class="glyphicon glyphicon-pencil"></span> ' . 'Edit',
				[ 'update', 'id' => $model->id],
				['class' => 'btn btn-info']
			) ?>



			<?= Html::a(
				'<span class="glyphicon glyphicon-plus"></span> ' . 'Import Pilot Entries',
				['import', 'id' => $model->id],
				['class' => 'btn btn-success']
			) ?>

		</div>

		<div class="pull-right">
			<?= Html::a('<span class="glyphicon glyphicon-list"></span> '
				. 'Full list', ['index'], ['class'=>'btn btn-default']) ?>
		</div>

	</div>

	<hr/>

	<?php $this->beginBlock('\app\models\Contest'); ?>


	<?= DetailView::widget([
		'model' => $model,
		'attributes' => [
			// generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::attributeFormat
			[
				'format' => 'html',
				'attribute' => 'club_id',
				'value' => ($model->club ?
					Html::a('<i class="glyphicon glyphicon-list"></i>', ['club/index']).' '.
					Html::a('<i class="glyphicon glyphicon-circle-arrow-right"></i> '.$model->club->name, ['club/view', 'id' => $model->club->id,]).' '.
					Html::a('<i class="glyphicon glyphicon-paperclip"></i>', ['create', 'Contest'=>['club_id' => $model->club_id]])
					:
					'<span class="label label-warning">?</span>'),
			],
			'name',
			'start',
			'end',
			'gnz_id',
		],
	]); ?>


	<hr/>

	<?= Html::a(
		'<span class="glyphicon glyphicon-trash"></span> ' . 'Delete',
		['delete', 'id' => $model->id],
		[
			'class' => 'btn btn-danger',
			'data-confirm' => '' . 'Are you sure to delete this item?' . '',
			'data-method' => 'post',
		]
	); ?>
	<?php $this->endBlock(); ?>



	<?php $this->beginBlock('Pilots'); ?>
	<div style='position: relative'>
		<div style='position:absolute; right: 0px; top: 0px;'>
			<?= Html::a(
				'<span class="glyphicon glyphicon-list"></span> ' . 'List All' . ' Pilots',
				['pilot/index'],
				['class'=>'btn text-muted btn-xs']
			) ?>
			<?= Html::a(
				'<span class="glyphicon glyphicon-plus"></span> ' . 'New' . ' Pilot',
				['pilot/create', 'Pilot' => ['contest_id' => $model->id]],
				['class'=>'btn btn-success btn-xs']
			); ?>
		</div>
	</div>
	<?php Pjax::begin(['id'=>'pjax-Pilots', 'enableReplaceState'=> false, 'linkSelector'=>'#pjax-Pilots ul.pagination a, th a']) ?>
	<?=
	'<div class="table-responsive">'
	. \yii\grid\GridView::widget([
		'layout' => '{summary}<div class="text-center">{pager}</div>{items}<div class="text-center">{pager}</div>',
		'dataProvider' => new \yii\data\ActiveDataProvider([
			'query' => $model->getPilots(),
			'pagination' => [
				'pageSize' => 20,
				'pageParam'=>'page-pilots',
			]
		]),
		'pager'        => [
			'class'          => yii\widgets\LinkPager::className(),
			'firstPageLabel' => 'First',
			'lastPageLabel'  => 'Last'
		],
		'columns' => [
			'id',
			'gnz_id',
			'name',
			'address1',
			'address2',
			'address3',
			'postcode',
			'telephone',
			'rego',
			[
				'class'      => 'yii\grid\ActionColumn',
				'template'   => '{view} {update}',
				'contentOptions' => ['nowrap'=>'nowrap'],
				'urlCreator' => function ($action, $model, $key, $index) {
					// using the column name as key, not mapping to 'id' like the standard generator
					$params = is_array($key) ? $key : [$model->primaryKey()[0] => (string) $key];
					$params[0] = 'pilot' . '/' . $action;
					$params['Pilot'] = ['contest_id' => $model->primaryKey()[0]];
					return $params;
				},
				'buttons'    => [

				],
				'controller' => 'pilot'
			],
		]
	])
	. '</div>'
	?>
	<?php Pjax::end() ?>
	<?php $this->endBlock() ?>


	<?php $this->beginBlock('Towplanes'); ?>
	<div style='position: relative'>
		<div style='position:absolute; right: 0px; top: 0px;'>
			<?= Html::a(
				'<span class="glyphicon glyphicon-list"></span> ' . 'List All' . ' Towplanes',
				['towplane/index'],
				['class'=>'btn text-muted btn-xs']
			) ?>
			<?= Html::a(
				'<span class="glyphicon glyphicon-plus"></span> ' . 'New' . ' Towplane',
				['towplane/create', 'Towplane' => ['contest_id' => $model->id]],
				['class'=>'btn btn-success btn-xs']
			); ?>
		</div>
	</div>
	<?php Pjax::begin(['id'=>'pjax-Towplanes', 'enableReplaceState'=> false, 'linkSelector'=>'#pjax-Towplanes ul.pagination a, th a']) ?>
	<?=
	'<div class="table-responsive">'
	. \yii\grid\GridView::widget([
		'layout' => '{summary}<div class="text-center">{pager}</div>{items}<div class="text-center">{pager}</div>',
		'dataProvider' => new \yii\data\ActiveDataProvider([
			'query' => $model->getTowplanes(),
			'pagination' => [
				'pageSize' => 20,
				'pageParam'=>'page-towplanes',
			]
		]),
		'pager'        => [
			'class'          => yii\widgets\LinkPager::className(),
			'firstPageLabel' => 'First',
			'lastPageLabel'  => 'Last'
		],
		'columns' => [
			'id',
			'rego',
			'description',
			'name',
			'address1',
			'address2',
			'address3',
			'postcode',
			'telephone',
			[
				'class'      => 'yii\grid\ActionColumn',
				'template'   => '{view} {update}',
				'contentOptions' => ['nowrap'=>'nowrap'],
				'urlCreator' => function ($action, $model, $key, $index) {
					// using the column name as key, not mapping to 'id' like the standard generator
					$params = is_array($key) ? $key : [$model->primaryKey()[0] => (string) $key];
					$params[0] = 'towplane' . '/' . $action;
					$params['Towplane'] = ['contest_id' => $model->primaryKey()[0]];
					return $params;
				},
				'buttons'    => [

				],
				'controller' => 'towplane'
			],
		]
	])
	. '</div>'
	?>
	<?php Pjax::end() ?>
	<?php $this->endBlock() ?>


	<?php $this->beginBlock('TransactionTypes'); ?>
	<div style='position: relative'>
		<div style='position:absolute; right: 0px; top: 0px;'>
			<?= Html::a(
				'<span class="glyphicon glyphicon-list"></span> ' . 'List All' . ' Transaction Types',
				['transaction-type/index'],
				['class'=>'btn text-muted btn-xs']
			) ?>
			<?= Html::a(
				'<span class="glyphicon glyphicon-plus"></span> ' . 'New' . ' Transaction Type',
				['transaction-type/create', 'TransactionType' => ['contest_id' => $model->id]],
				['class'=>'btn btn-success btn-xs']
			); ?>
		</div>
	</div>
	<?php Pjax::begin(['id'=>'pjax-TransactionTypes', 'enableReplaceState'=> false, 'linkSelector'=>'#pjax-TransactionTypes ul.pagination a, th a']) ?>
	<?=
	'<div class="table-responsive">'
	. \yii\grid\GridView::widget([
		'layout' => '{summary}<div class="text-center">{pager}</div>{items}<div class="text-center">{pager}</div>',
		'dataProvider' => new \yii\data\ActiveDataProvider([
			'query' => $model->getTransactionTypes(),
			'pagination' => [
				'pageSize' => 20,
				'pageParam'=>'page-transactiontypes',
			]
		]),
		'pager'        => [
			'class'          => yii\widgets\LinkPager::className(),
			'firstPageLabel' => 'First',
			'lastPageLabel'  => 'Last'
		],
		'columns' => [
			'id',
			'name',
			'description',
			'price',
			'credit',
			[
				'class'      => 'yii\grid\ActionColumn',
				'template'   => '{view} {update}',
				'contentOptions' => ['nowrap'=>'nowrap'],
				'urlCreator' => function ($action, $model, $key, $index) {
					// using the column name as key, not mapping to 'id' like the standard generator
					$params = is_array($key) ? $key : [$model->primaryKey()[0] => (string) $key];
					$params[0] = 'transaction-type' . '/' . $action;
					$params['TransactionType'] = ['contest_id' => $model->primaryKey()[0]];
					return $params;
				},
				'buttons'    => [

				],
				'controller' => 'transaction-type'
			],
		]
	])
	. '</div>'
	?>
	<?php Pjax::end() ?>
	<?php $this->endBlock() ?>


	<?= Tabs::widget(
		[
			'id' => 'relation-tabs',
			'encodeLabels' => false,
			'items' => [
				[
					'label'   => '<b class=""># '.Html::encode($model->id).'</b>',
					'content' => $this->blocks['\app\models\Contest'],
					'active'  => true,
				],
				[
					'content' => $this->blocks['Pilots'],
					'label'   => '<small>Pilots <span class="badge badge-default">'. $model->getPilots()->count() . '</span></small>',
					'active'  => false,
				],
				[
					'content' => $this->blocks['Towplanes'],
					'label'   => '<small>Towplanes <span class="badge badge-default">'. $model->getTowplanes()->count() . '</span></small>',
					'active'  => false,
				],
				[
					'content' => $this->blocks['TransactionTypes'],
					'label'   => '<small>Transaction Types <span class="badge badge-default">'. $model->getTransactionTypes()->count() . '</span></small>',
					'active'  => false,
				],
			]
		]
	);
	?>
</div>
